[project]
name = "yolo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cvzone>=1.6.1",
    "ncnn>=1.0.20260114",
    "pnnx>=20260112",
    "ultralytics>=8.4.14",
]
