[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "onnxruntime>=1.24.1",
    "opencv-python>=4.13.0.92",
    "psutil>=7.2.2",
    "yolo>=0.3.1",
]

[tool.uv]
system-site-packages = true
